parameters:
  name: ''
  vmImage: ''
  pyVersions: [3.5, 3.6, 3.7]
  packages:
    - name: 'fairlearn-core'
      extensions: '[test,devenv,doc]'
    - name: 'fairlearn-core'
      extensions: '[postprocessingplot,test,devenv,doc]'
    - name: 'fairlearn'
      extensions: '[test,devenv,doc]'
  pinRequirements: False
  freezeArtifactStem: 
  freezeFileStem:

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    maxParallel: 2
    matrix:
      ${{ each pyVer in parameters.pyVersions }}:
        ${{ each package in parameters.packages }}:
          '${{ pyVer }}-${{ package }}':
            PyVer: ${{ pyVer }}
            FreezeArtifact: '${{parameters.freezeArtifactStem}}${{parameters.name}}${{pyVer}}'
            FreezeFile: '${{parameters.freezeFileStem}}-${{parameters.name}}${{pyVer}}.txt'
            Package: ${{ package.name }}
            PackageExtensions: ${{ package.extensions}}

  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(PyVer)'
    inputs:
      versionSpec: '$(PyVer)' 
      addToPath: true

  - template: python-infra-upgrade-steps-template.yml

  - template: requirements-pin-steps-template.yml

  - template: pip-install-steps-template.yml

  - template: pip-freeze-to-artifact-steps-template.yml
    parameters:
      freezeArtifact: $(FreezeArtifact)
      freezeFile: $(FreezeFile)
    
  - script: flake8 .
    displayName: "Run flake8"

  - script: python -m pytest test/ --ignore=test/perf --junitxml=./TEST--TEST.xml -o junit_suite_name="$(Agent.JobName)"
    displayName: 'Run tests'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results **/TEST-*.xml'
    condition: succeededOrFailed()